// Copyright (c) 2026 The microtel Authors.
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <cstdint>
#include <string_view>

namespace microtel
{

/// @file version.hpp
/// @brief Version constants for the microtel runtime.
///
/// In production builds this header is generated by CMake from the project
/// version metadata. The hand-written form here is the M0 placeholder.

inline constexpr std::uint32_t kVersionMajor = 0;
inline constexpr std::uint32_t kVersionMinor = 1;
inline constexpr std::uint32_t kVersionPatch = 0;

inline constexpr std::string_view kVersionString = "0.1.0-m0";

}  // namespace microtel
